# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster
WORKDIR /broadbandequity
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .
# and then shell command to run depends on what we want to happen exactly...
CMD ["jupyter", "notebook", "--port=8889", "--no-browser", "--ip=0.0.0.0", "--allow-root"]